![Large120.jpg]()

## E.Coli DNA classification

In this project, We'll use support vector machines algorithim in order to    classify short E.Coli DNA sequences.

E.Coli dataset was downloaded from the UCI Machine Learning Repository that has 106 DNA sequences, with 57 sequential nucleotides (“base-pairs”) each.

Required packages

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.gaussian_process.kernels import RBF
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold, cross_val_score

Importing the Dataset

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/molecular-biology/promoter-gene-sequences/promoters.data'
names = ['Class', 'id', 'Sequence']
df = pd.read_csv(url, names = names)

In [ ]:
df.head()

  Class         id                                           Sequence
0     +        S10  \t\ttactagcaatacgcttgcgttcggtggttaagtatgtataat...
1     +       AMPC  \t\ttgctatcctgacagttgtcacgctgattggtgtcgttacaat...
2     +       AROH  \t\tgtactagagaactagtgcattagcttatttttttgttatcat...
3     +      DEOP2  \taattgtgatgtgtatcgaagtgtgttgcggagtagatgttagaa...
4     +  LEU1_TRNA  \ttcgataattaactattgacgaaaagctgaaaaccactagaatgc...

In [ ]:
df.shape

(106, 3)

In [ ]:
df.describe()

       Class    id                                           Sequence
count    106   106                                                106
unique     2   106                                                106
top        -   751  \t\tttagagagcatgtcagcctcgacaacttgcataaatgctttc...
freq      53     1                                                  1

## Preprocessing the Dataset

The data is not in a usable form; as a result, we will need to process it before using it to train our algorithms.

In [ ]:
# Build our dataset using custom pandas dataframe
clases = df.loc[:,'Class']
# generate list of DNA sequence
sequence = list(df.loc[:, 'Sequence'])
sequence

['\t\ttactagcaatacgcttgcgttcggtggttaagtatgtataatgcgcgggcttgtcgt',
 '\t\ttgctatcctgacagttgtcacgctgattggtgtcgttacaatctaacgcatcgccaa',
 '\t\tgtactagagaactagtgcattagcttatttttttgttatcatgctaaccacccggcg',
 '\taattgtgatgtgtatcgaagtgtgttgcggagtagatgttagaatactaacaaactc',
 '\ttcgataattaactattgacgaaaagctgaaaaccactagaatgcgcctccgtggtag',
 '\taggggcaaggaggatggaaagaggttgccgtataaagaaactagagtccgtttaggt',
 '\t\tcagggggtggaggatttaagccatctcctgatgacgcatagtcagcccatcatgaat',
 '\t\ttttctacaaaacacttgatactgtatgagcatacagtataattgcttcaacagaaca',
 '\t\tcgacttaatatactgcgacaggacgtccgttctgtgtaaatcgcaatgaaatggttt',
 '\tttttaaatttcctcttgtcaggccggaataactccctataatgcgccaccactgaca',
 '\tgcaaaaataaatgcttgactctgtagcgggaaggcgtattatgcacaccccgcgccg',
 '\tcctgaaattcagggttgactctgaaagaggaaagcgtaatatacgccacctcgcgac',
 '\tgatcaaaaaaatacttgtgcaaaaaattgggatccctataatgcgcctccgttgaga',
 '\tctgcaatttttctattgcggcctgcggagaactccctataatgcgcctccatcgaca',
 '\ttttatatttttcgcttgtcaggccggaataactccctataatgcgccaccactgaca',
 '\taagcaaagaaatgcttgactctgtagcgggaaggcgtattatgcacaccgccgcgcc',
 '\tatgcatttttccgcttgtcttcctgagccgactccctataatgcgcctccatcgaca',
 '\t\taaacaatttcagaatagacaaaaactctgagtgtaataatgtagcctcgtgtcttgc',
 '\t\ttctcaacgtaacactttacagcggcgcgtcatttgatatgatgcgccccgcttcccg',
 '\t\tgcaaataatcaatgtggacttttctgccgtgattatagacacttttgttacgcgttt',
 '\t\tgacaccatcgaatggcgcaaaacctttcgcggtatggcatgatagcgcccggaagag',
 '\t\taaaaacgtcatcgcttgcattagaaaggtttctggccgaccttataaccattaatta',
 '\t\ttctgaaatgagctgttgacaattaatcatcgaactagttaactagtacgcaagttca',
 '\taccggaagaaaaccgtgacattttaacacgtttgttacaaggtaaaggcgacgccgc',
 '\t\taaattaaaattttattgacttaggtcactaaatactttaaccaatataggcatagcg',
 '\t\tttgtcataatcgacttgtaaaccaaattgaaaagatttaggtttacaagtctacacc',
 '\t\tcatcctcgcaccagtcgacgacggtttacgctttacgtatagtggcgacaatttttt',
 '\ttccagtataatttgttggcataattaagtacgacgagtaaaattacatacctgcccg',
 '\tacagttatccactattcctgtggataaccatgtgtattagagttagaaaacacgagg',
 '\t\ttgtgcagtttatggttccaaaatcgccttttgctgtatatactcacagcataactgt',
 '\tctgttgttcagtttttgagttgtgtataacccctcattctgatcccagcttatacgg',
 '\tattacaaaaagtgctttctgaactgaacaaaaaagagtaaagttagtcgcgtagggt',
 '\tatgcgcaacgcggggtgacaagggcgcgcaaaccctctatactgcgcgccgaagctg',
 '\t\ttaaaaaactaacagttgtcagcctgtcccgcttataagatcatacgccgttatacgt',
 '\t\tatgcaattttttagttgcatgaactcgcatgtctccatagaatgcgcgctacttgat',
 '\tccttgaaaaagaggttgacgctgcaaggctctatacgcataatgcgccccgcaacgc',
 '\t\ttcgttgtatatttcttgacaccttttcggcatcgccctaaaattcggcgtcctcata',
 '\t\tccgtttattttttctacccatatccttgaagcggtgttataatgccgcgccctcgat',
 '\t\tttcgcatatttttcttgcaaagttgggttgagctggctagattagccagccaatctt',
 '\t\ttgtaaactaatgcctttacgtgggcggtgattttgtctacaatcttacccccacgta',
 '\tgatcgcacgatctgtatacttatttgagtaaattaacccacgatcccagccattctt',
 '\t\taacgcatacggtattttaccttcccagtcaagaaaacttatcttattcccacttttc',
 '\tttagcggatcctacctgacgctttttatcgcaactctctactgtttctccatacccg',
 '\t\tgccttctccaaaacgtgttttttgttgttaattcggtgtagacttgtaaacctaaat',
 '\tcagaaacgttttattcgaacatcgatctcgtcttgtgttagaattctaacatacggt',
 '\tcactaatttattccatgtcacacttttcgcatctttgttatgctatggttatttcat',
 '\t\tatataaaaaagttcttgctttctaacgtgaaagtggtttaggttaaaagacatcagt',
 '\t\tcaaggtagaatgctttgccttgtcggcctgattaatggcacgatagtcgcatcggat',
 '\tggccaaaaaatatcttgtactatttacaaaacctatggtaactctttaggcattcct',
 '\ttaggcaccccaggctttacactttatgcttccggctcgtatgttgtgtggaattgtg',
 '\t\tccatcaaaaaaatattctcaacataaaaaactttgtgtaatacttgtaacgctacat',
 '\t\ttggggacgtcgttactgatccgcacgtttatgatatgctatcgtactctttagcgag',
 '\ttcagaaatattatggtgatgaactgtttttttatccagtataatttgttggcataat',
 '\t\tatatgaacgttgagactgccgctgagttatcagctgtgaacgacattctggcgtcta',
 '\t\tcgaacgagtcaatcagaccgctttgactctggtattactgtgaacattattcgtctc',
 '\t\tcaatggcctctaaacgggtcttgaggggttttttgctgaaaggaggaactatatgcg',
 '\t\tttgacctactacgccagcattttggcggtgtaagctaaccattccggttgactcaat',
 '\t\tcgtctatcggtgaacctccggtatcaacgctggaaggtgacgctaacgcagatgcag',
 '\t\tgccaatcaatcaagaacttgaagggtggtatcagccaacagcctgacatccttcgtt',
 '\t\ttggatggacgttcaacattgaggaaggcataacgctactacctgatgtttactccaa',
 '\t\tgaggtggctatgtgtatgaccgaacgagtcaatcagaccgctttgactctggtatta',
 '\t\tcgtagcgcatcagtgctttcttactgtgagtacgcaccagcgccagaggacgacgac',
 '\t\tcgaccgaagcgagcctcgtcctcaatggcctctaaacgggtcttgaggggttttttg',
 '\t\tctacggtgggtacaatatgctggatggagatgcgttcacttctggtctactgactcg',
 '\t\tatagtctcagagtcttgacctactacgccagcattttggcggtgtaagctaaccatt',
 '\t\taactcaaggctgatacggcgagacttgcgagccttgtccttgcggtacacagcagcg',
 '\t\tttactgtgaacattattcgtctccgcgactacgatgagatgcctgagtgcttccgtt',
 '\t\ttattctcaacaagattaaccgacagattcaatctcgtggatggacgttcaacattga',
 '\t\taacgagtcaatcagaccgctttgactctggtattactgtgaacattattcgtctccg',
 '\t\taagtgcttagcttcaaggtcacggatacgaccgaagcgagcctcgtcctcaatggcc',
 '\t\tgaagaccacgcctcgccaccgagtagacccttagagagcatgtcagcctcgacaact',
 '\t\tttagagagcatgtcagcctcgacaacttgcataaatgctttcttgtagacgtgccct',
 '\t\ttattcgtctccgcgactacgatgagatgcctgagtgcttccgttactggattgtcac',
 '\t\ttgctgaaaggaggaactatatgcgctcatacgatatgaacgttgagactgccgctga',
 '\t\tcatgaactcaaggctgatacggcgagacttgcgagccttgtccttgcggtacacagc',
 '\t\tttcgtctccgcgactacgatgagatgcctgagtgcttccgttactggattgtcacca',
 '\t\tcatgtcagcctcgacaacttgcataaatgctttcttgtagacgtgccctacgcgctt',
 '\t\taggaggaactacgcaaggttggaacatcggagagatgccagccagcgcacctgcacg',
 '\t\ttctcaacaagattaaccgacagattcaatctcgtggatggacgttcaacattgagga',
 '\t\ttgaagtgcttagcttcaaggtcacggatacgaccgaagcgagcctcgtcctcaatgg',
 '\t\tctatatgcgctcatacgatatgaacgttgagactgccgctgagttatcagctgtgaa',
 '\t\tgcggcagcacgtttccacgcggtgagagcctcaggattcatgtcgatgtcttccggt',
 '\t\tatccctaatgtctacttccggtcaatccatctacgttaaccgaggtggctatgtgta',
 '\t\ttggcgtctatcggtgaacctccggtatcaacgctggaaggtgacgctaacgcagatg',
 '\t\ttctcgtggatggacgttcaacattgaggaaggcataacgctactacctgatgtttac',
 '\t\ttattggcttgctcaagcatgaactcaaggctgatacggcgagacttgcgagccttgt',
 '\t\ttagagggtgtactccaagaagaggaagatgaggctagacgtctctgcatggagtatg',
 '\t\tcagcggcagcacgtttccacgcggtgagagcctcaggattcatgtcgatgtcttccg',
 '\t\tttacgttggcgaccgctaggactttcttgttgattttccatgcggtgttttgcgcaa',
 '\t\tacgctaacgcagatgcagcgaacgctcggcgtattctcaacaagattaaccgacaga',
 '\t\tggtgttttgcgcaatgttaatcgctttgtacacctcaggcatgtaaacgtcttcgta',
 '\t\taaccattccggttgactcaatgagcatctcgatgcagcgtactcctacatgaataga',
 '\t\tagacgtctctgcatggagtatgagatggactacggtgggtacaatatgctggatgga',
 '\t\ttgttgattttccatgcggtgttttgcgcaatgttaatcgctttgtacacctcaggca',
 '\t\ttgcacgggttgcgatagcctcagcgtattcaggtgcgagttcgatagtctcagagtc',
 '\t\taggcatgtaaacgtcttcgtagcgcatcagtgctttcttactgtgagtacgcaccag',
 '\t\tccgagtagacccttagagagcatgtcagcctcgacaacttgcataaatgctttcttg',
 '\t\tcgctaggactttcttgttgattttccatgcggtgttttgcgcaatgttaatcgcttt',
 '\t\ttatgaccgaacgagtcaatcagaccgctttgactctggtattactgtgaacattatt',
 '\t\tagagggtgtactccaagaagaggaagatgaggctagacgtctctgcatggagtatga',
 '\t\tgagagcatgtcagcctcgacaacttgcataaatgctttcttgtagacgtgccctacg',
 '\t\tcctcaatggcctctaaacgggtcttgaggggttttttgctgaaaggaggaactatat',
 '\t\tgtattctcaacaagattaaccgacagattcaatctcgtggatggacgttcaacattg',
 '\t\tcgcgactacgatgagatgcctgagtgcttccgttactggattgtcaccaaggcttcc',
 '\t\tctcgtcctcaatggcctctaaacgggtcttgaggggttttttgctgaaaggaggaac',
 '\t\ttaacattaataaataaggaggctctaatggcactcattagccaatcaatcaagaact']

In [ ]:
#Remove tab from each sequence
dic = {}
for k, seq in enumerate(sequence):
    nucleotides = list(seq)
    nucleotides = [char for char in nucleotides if char != '\t']
    #append class assignment
    nucleotides.append(clases[k])
    
    dic[k] = nucleotides

In [ ]:
dic[1]

['t',
 'g',
 'c',
 't',
 'a',
 't',
 'c',
 'c',
 't',
 'g',
 'a',
 'c',
 'a',
 'g',
 't',
 't',
 'g',
 't',
 'c',
 'a',
 'c',
 'g',
 'c',
 't',
 'g',
 'a',
 't',
 't',
 'g',
 'g',
 't',
 'g',
 't',
 'c',
 'g',
 't',
 't',
 'a',
 'c',
 'a',
 'a',
 't',
 'c',
 't',
 'a',
 'a',
 'c',
 'g',
 'c',
 'a',
 't',
 'c',
 'g',
 'c',
 'c',
 'a',
 'a',
 '+']

In [ ]:
# Convert Dict  into a  dataframe
data = pd.DataFrame(dic)
data.shape

(58, 106)

In [ ]:
# transpose dataframe into correct format
data = data.transpose()
data.shape

(106, 58)

In [ ]:
data.head()

  0  1  2  3  4  5  6  7  8  9  10 11 12  ... 45 46 47 48 49 50 51 52 53 54 55 56 57
0  t  a  c  t  a  g  c  a  a  t  a  c  g  ...  c  g  g  g  c  t  t  g  t  c  g  t  +
1  t  g  c  t  a  t  c  c  t  g  a  c  a  ...  a  c  g  c  a  t  c  g  c  c  a  a  +
2  g  t  a  c  t  a  g  a  g  a  a  c  t  ...  a  a  c  c  a  c  c  c  g  g  c  g  +
3  a  a  t  t  g  t  g  a  t  g  t  g  t  ...  a  c  t  a  a  c  a  a  a  c  t  c  +
4  t  c  g  a  t  a  a  t  t  a  a  c  t  ...  c  c  t  c  c  g  t  g  g  t  a  g  +

[5 rows x 58 columns]

In [ ]:
# Rename
data.rename(columns = {57:'Class'}, inplace = True)

In [ ]:
data['Class']

0      +
1      +
2      +
3      +
4      +
      ..
101    -
102    -
103    -
104    -
105    -
Name: Class, Length: 106, dtype: object

In [ ]:
data.columns

Index([      0,       1,       2,       3,       4,       5,       6,       7,
             8,       9,      10,      11,      12,      13,      14,      15,
            16,      17,      18,      19,      20,      21,      22,      23,
            24,      25,      26,      27,      28,      29,      30,      31,
            32,      33,      34,      35,      36,      37,      38,      39,
            40,      41,      42,      43,      44,      45,      46,      47,
            48,      49,      50,      51,      52,      53,      54,      55,
            56, 'Class'],
      dtype='object')

In [ ]:
data.head()

   0  1  2  3  4  5  6  7  8  9 10 11  ... 46 47 48 49 50 51 52 53 54 55 56 Class
0  t  a  c  t  a  g  c  a  a  t  a  c  ...  g  g  g  c  t  t  g  t  c  g  t     +
1  t  g  c  t  a  t  c  c  t  g  a  c  ...  c  g  c  a  t  c  g  c  c  a  a     +
2  g  t  a  c  t  a  g  a  g  a  a  c  ...  a  c  c  a  c  c  c  g  g  c  g     +
3  a  a  t  t  g  t  g  a  t  g  t  g  ...  c  t  a  a  c  a  a  a  c  t  c     +
4  t  c  g  a  t  a  a  t  t  a  a  c  ...  c  t  c  c  g  t  g  g  t  a  g     +

[5 rows x 58 columns]

In [ ]:
#Encoding
numerical_df = pd.get_dummies(data)
numerical_df.head()

   0_a  0_c  0_g  0_t  1_a  1_c  ...  56_a  56_c  56_g  56_t  Class_+  Class_-
0    0    0    0    1    1    0  ...     0     0     0     1        1        0
1    0    0    0    1    0    0  ...     1     0     0     0        1        0
2    0    0    1    0    0    0  ...     0     0     1     0        1        0
3    1    0    0    0    1    0  ...     0     1     0     0        1        0
4    0    0    0    1    0    1  ...     0     0     1     0        1        0

[5 rows x 230 columns]

In [ ]:
# Drop class_- or Class_+ either of one
numerical_df.drop('Class_-', axis = 1, inplace = True)

In [ ]:
# rename Class_+ to Class
numerical_df.rename(columns = {'Class_+':'Class'}, inplace = True)

## Training and Testing the Classification Algorithm

Splitting data

In [ ]:
X = numerical_df.drop(['Class'], axis = 1).values
y = numerical_df['Class'].values

#define a seed for reproducibility
seed = 1

# Splitting data into the training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = seed)

In [ ]:
# Define scoring method
scoring = 'accuracy'
# Model building to train
names = ['SVM Linear', 'SVM RBF', 'SVM Sigmoid']
Classifiers = [
    svm.SVC(kernel = 'linear'),
    svm.SVC(kernel = 'rbf'),
    svm.SVC(kernel = 'sigmoid')
    
    ]
models = zip(names, Classifiers)

names = []
result = []
for name, model in models:
    kfold = KFold(n_splits = 10, random_state = 1, shuffle=True)
    cv_results = cross_val_score(model, X_train, y_train, cv = kfold, scoring = 'accuracy')
    result.append(cv_results)
    names.append(name)
    msg = "{0}: {1} ({2})".format(name, cv_results.mean(), cv_results.std())
    print(msg)

SVM Linear: 0.9125 (0.09762812094883318)
SVM RBF: 0.875 (0.11180339887498948)
SVM Sigmoid: 0.925 (0.1)

## The Model's Evaluation

In [ ]:


#Test the algorithm on the test data set
models = zip(names, Classifiers)
for name, model in models:
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(name)
    print(accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))

SVM Linear
0.9629629629629629
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        17
           1       0.91      1.00      0.95        10

    accuracy                           0.96        27
   macro avg       0.95      0.97      0.96        27
weighted avg       0.97      0.96      0.96        27

SVM RBF
0.9259259259259259
              precision    recall  f1-score   support

           0       1.00      0.88      0.94        17
           1       0.83      1.00      0.91        10

    accuracy                           0.93        27
   macro avg       0.92      0.94      0.92        27
weighted avg       0.94      0.93      0.93        27

SVM Sigmoid
0.9259259259259259
              precision    recall  f1-score   support

           0       1.00      0.88      0.94        17
           1       0.83      1.00      0.91        10

    accuracy                           0.93        27
   macro avg       0.92      0.94      0.92        27
weighted avg       0.94      0.93      0.93        27

Support Vector Machine with 'linear' kernel performed best with F1_score = 0.96 on testing data.

## Run SVM with linear kernel

Run SVM with linear kernel and C=1.0

In [ ]:
# instantiate classifier with linear kernel and C=1.0
linear_svc=SVC(kernel='linear', C=1.0) 


# fit classifier to training set
linear_svc.fit(X_train,y_train)


# make predictions on test set
y_pred_test=linear_svc.predict(X_test)


# compute and print accuracy score
accuracy_score(y_test, y_pred_test)

0.9629629629629629

Run SVM with linear kernel and C=100.0

In [ ]:
# instantiate classifier with linear kernel and C=100.0
linear_svc100=SVC(kernel='linear', C=100.0) 


# fit classifier to training set
linear_svc100.fit(X_train, y_train)


# make predictions on test set
y_pred=linear_svc100.predict(X_test)


# compute and print accuracy score
accuracy_score(y_test, y_pred_test)

0.9629629629629629

## Run SVM with polynomial kernel

In [ ]:
# instantiate classifier with polynomial kernel and C=1.0
poly_svc=SVC(kernel='poly') 


# fit classifier to training set
poly_svc.fit(X_train,y_train)


# make predictions on test set
y_pred=poly_svc.predict(X_test)


# compute and print accuracy score
print('Model accuracy score with polynomial kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with polynomial kernel and C=1.0 : 0.8889



Polynomial kernel gives poor performance.

##  Hyperparameter Optimization using GridSearch CV

In [ ]:
# import GridSearchCV
from sklearn.model_selection import GridSearchCV


# import SVC classifier
from sklearn.svm import SVC


# instantiate classifier with default hyperparameters with kernel=rbf, C=1.0 and gamma=auto
svc=SVC() 



# declare parameters for hyperparameter tuning
parameters = [ {'C':[1, 10, 100, 1000], 'kernel':['linear']},
               {'C':[1, 10, 100, 1000], 'kernel':['rbf'], 'gamma':[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]},
               {'C':[1, 10, 100, 1000], 'kernel':['poly'], 'degree': [2,3,4] ,'gamma':[0.01,0.02,0.03,0.04,0.05]} 
              ]




grid_search = GridSearchCV(estimator = svc,  
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 5,
                           verbose=0)


grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000],
                          'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
                                    0.9],
                          'kernel': ['rbf']},
                         {'C': [1, 10, 100, 1000], 'degree': [2, 3, 4],
                          'gamma': [0.01, 0.02, 0.03, 0.04, 0.05],
                          'kernel': ['poly']}],
             scoring='accuracy')

In [ ]:
# examine the best model


# best score achieved during the GridSearchCV
print('GridSearch CV best score : {:.4f}\n\n'.format(grid_search.best_score_))


# print parameters that give the best results
print('Parameters that give the best results :','\n\n', (grid_search.best_params_))


# print estimator that was chosen by the GridSearch
print('\n\nEstimator that was chosen by the search :','\n\n', (grid_search.best_estimator_))

GridSearch CV best score : 0.9117


Parameters that give the best results :

 {'C': 1, 'degree': 2, 'gamma': 0.02, 'kernel': 'poly'}


Estimator that was chosen by the search :

 SVC(C=1, degree=2, gamma=0.02, kernel='poly')